# Generated by Django 2.0.13 on 2019-11-30 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eelections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='communes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eelections.Communes'),
            preserve_default=False,
        ),
    ]
