# Generated by Django 2.0.13 on 2019-11-30 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eelections', '0002_voters_communes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_on_list', models.IntegerField()),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('number_of_votes', models.IntegerField()),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eelections.Communes')),
            ],
        ),
        migrations.CreateModel(
            name='Constituencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voivodeship', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eelections.Constituencies')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionCommittes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('drawn_number', models.IntegerField()),
                ('number_of_votes', models.IntegerField()),
                ('nov_in_percents', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='voters',
            old_name='communes',
            new_name='commune',
        ),
        migrations.AddField(
            model_name='candidates',
            name='election_committe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eelections.ElectionCommittes'),
        ),
        migrations.AddField(
            model_name='communes',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eelections.Counties'),
            preserve_default=False,
        ),
    ]
